### ISSUE TITLE
Error with requirements.txt

### ISSUE THREAD

**Issue by SgtD-SOD** [SenyxLois/KeyboxCheckerPython#1]
![Screenshot_20241118-130829](https://github.com/user-attachments/assets/cd0e73db-b129-4701-af1c-dd3bc6249426)

**Comment by SenyxLois** [comment]
There is currently an issue with cryptography on pip. Use this command to fix it :
```bash
export RUSTFLAGS=" -C lto=no" && export CARGO_BUILD_TARGET="$(rustc -vV | sed -n 's|host: ||p')" && pip install cryptography aiohttp colorama
```

This command work for me. If it work for you please let me know as I will include this on the markdown file
