### ISSUE TITLE
False positive (negative?)

### ISSUE THREAD

**Issue by SgtD-SOD** [SenyxLois/KeyboxCheckerPython#4]
![Screenshot_20241120-074526~2](https://github.com/user-attachments/assets/d5701413-8302-4e9a-8ae6-bb8edc66da1d)
![Screenshot_20241120-074539](https://github.com/user-attachments/assets/139589ab-672b-4860-92f9-ec9de277e16c)

**Comment by SenyxLois** [comment]
Currently fixing this

**Comment by SenyxLois** [comment]
Issue has been fixed. Please get the latest version
